export const FETCH_ALL_MOVIES_REQ = "FETCH_ALL_MOVIES_REQ";
export const FETCH_ALL_MOVIES = "FETCH_ALL_MOVIES";
export const FETCHED_ALL_MOVIES = "FETCHED_ALL_MOVIES";
export const SEND_MOVIE_QUERY_REQ = "SEND_MOVIE_QUERY_REQ";
export const SEND_MOVIE_QUERY = 'SEND_MOVIE_QUERY';
export const FETCHED_MOVIE_RESPONSE = 'FETCHED_MOVIE_RESPONSE';